### ISSUE TITLE
errore in console, negozio auto

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#102]
mi è uscito questo spam di errore in console quando ho aperto il menù del concessionario
![image](https://user-images.githubusercontent.com/102382815/162561549-b4c5470f-3b7f-4cfd-a507-5e3fd88f264d.png)

**Comment by Gregosso** [comment]
sembra essere errori su un'altro server, noi non abbiamo nessuna risorsa con krz_personalmenu
