### ISSUE TITLE
immagini mancanti al concessionario 

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#105]
![image](https://user-images.githubusercontent.com/102382815/162576301-f3f3d291-878a-4882-ad95-dfb1901b6de9.png)
![image](https://user-images.githubusercontent.com/102382815/162576339-19437189-7be9-4942-a76f-eedb20f9dcb4.png)

**Comment by rendy6416** [comment]
Burrito sistemato

**Comment by rendy6416** [comment]
Aggiunto anche la scirocco
