### ISSUE TITLE
errore console pompieri

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#107]
mettendo il veicolo dei pompieri nel garage mi è uscito questo errore
![image](https://user-images.githubusercontent.com/102382815/162613306-9760177c-65d7-4ca7-93b2-6b0d62c48534.png)

**Comment by Enderic3** [comment]
![image](https://user-images.githubusercontent.com/102382815/162613322-38913648-5b8b-4a0e-92b2-bb31d348a3b0.png)

**Comment by stubfx** [comment]
Impossibile da verificare aggiungere dettagli se possibile

**Comment by Enderic3** [comment]
ho comprato l'auto dei pompieri ed mi ci sono attaccato per spruzzare l'acqua, poi lo ho riposto nel garage
