### ISSUE TITLE
blip auto a noleggio

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#110]
aggiungere un blip per le auto a noleggio anche dove si spawna al centro impieghi

**Comment by stubfx** [comment]
Essendo tutto piuttosto vicino allo spawn e considerato che con i 25k di partenza un player può comprare legalmente una patente ed un auto in tempi ragionevoli (meno di 15 min) non ce necessita di avere un blip per le auto noleggio al centro impieghi.
Eventualmente un player volesse, ce sempre la possibilità di rubare un auto agli npc (con ovvie e eventuali conseguenze in game).
