### ISSUE TITLE
Visuale vestiario polizia

### ISSUE THREAD

**Issue by sasy992** [ProjectHorizonRP/public_issues#119]
è davvero molto brutto e difficile modificare i vestiti allo shop della polizia, la visuale rimane sempre così:
![image](https://user-images.githubusercontent.com/30809172/163562686-5a66cb2c-d6e9-47bf-9717-9f5b2cc24247.png)

Servirebbe la possibilità di vedere tutto con un angolazione diversa o con una free cam

**Comment by stubfx** [comment]
ho sempre odiato questo menu @Gregosso <3

**Comment by sasy992** [comment]
Anche io, odiato fin dal principio.
Almeno riusciamo a sbloccare la visuale?? In questo modo è davvero difficile

**Comment by sasy992** [comment]
con il tasto 4 e 6 è possibile spostare la visuale.
