### ISSUE TITLE
Nel terminale polizia le sanzioni non sono aggiornate

### ISSUE THREAD

**Issue by sasy992** [ProjectHorizonRP/public_issues#120]
Il terminale della polizia presenta dei prezzi non aggiornati con questo file: https://docs.google.com/spreadsheets/d/1bXolq4EuTb_I7tIJVljktd2eUM-Ick6u6tJkQWg9NOM/edit#gid=1880836981

**Comment by stubfx** [comment]
Chi ha scritto il file e quando è stato pubblicato?

**Comment by sasy992** [comment]
Immagino @Gregosso

**Comment by Gregosso** [comment]
Era un vecchio file che mi sono dimenticato di rimuovere, non bisogna tenerne conto. Verrà fatto nuovo in un secondo momento
