### ISSUE TITLE
Errore in console 

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#121]
mi è uscito questo errore in console, purtroppo non ho idea di come riprodurre tale errore
![image](https://user-images.githubusercontent.com/102382815/163601230-8fd2e17e-c808-4d5b-aaed-d10e2638cff0.png)

**Comment by stubfx** [comment]
stiamo indagando, @Gregosso credo sia correlato alla rottura dei veicoli

**Comment by Gregosso** [comment]
stavi fumando per caso se ti ricordi ? @Enderic3

**Comment by Enderic3** [comment]
mai prese le sigarette su sto server @Gregosso

**Comment by stubfx** [comment]
Non riesco a replicare l'errore, passo il bug in secondo piano perche non sembra aver dato problemi a nessuno ultimamente

**Comment by Gregosso** [comment]
Il bug è stato risolto con la issue ProjectHorizonRP/fivem#117
