### ISSUE TITLE
Troppi npc

### ISSUE THREAD

**Issue by sasy992** [ProjectHorizonRP/public_issues#122]
Secondo me ci sono troppi npc e veicoli in giro.. ridurrei la densità di questi

**Comment by stubfx** [comment]
Sono gia stati ridotti alla metà negli ultimi giorni, stiamo tenendo d'occhio il server per capire il peso che hanno sul server e sul role play in generale.

**Comment by stubfx** [comment]
@Gregosso

**Comment by sasy992** [comment]
Ridurrei ad un 20% di quelli che ci sarebbero in realtà , ovvero un 0.2
