### ISSUE TITLE
Terminale polizia senza nome operatore

### ISSUE THREAD

**Issue by sasy992** [ProjectHorizonRP/public_issues#123]
durante la compilazione non viene inserito in automatico (e neanche manualmente) il nome dell'operatore che ha compilato il rapporto di intervento 
![image](https://user-images.githubusercontent.com/30809172/163616274-2f491f2e-1e10-4138-93b9-413f760309dd.png)

**Comment by Gregosso** [comment]
Cambiato il terminale mdt
