### ISSUE TITLE
Terminale polizia non aggiorna i rapporti

### ISSUE THREAD

**Issue by sasy992** [ProjectHorizonRP/public_issues#126]
Se provo a modificare un rapporto nel terminale non salva le modifiche, se apro e chiudo il terminale la modifica non viene salvata
![image](https://user-images.githubusercontent.com/30809172/163624924-217945aa-f18b-4fb1-a52c-c7e8bba6dc4a.png)

**Comment by Gregosso** [comment]
Cambiato il terminale mdt
