### ISSUE TITLE
Bug menù tasto "?"

### ISSUE THREAD

**Issue by tonin994** [ProjectHorizonRP/public_issues#127]
**Nome su Discord**
GIgin

**Descrivi il problema**
Problema menù tasto "?" non si avvia e rimane bloccato

**Come riprodurre**
Passaggi per riprodurre il problema:
1. Sono andato davanti l'armeria
2. Sono sceso dalla moto
3. ho premuto il tasto "?" per guardare documenti
4. Hai errori in console? non sembra, intanto allego foto

**Screenshots**
![20220415214654_1](https://user-images.githubusercontent.com/78094144/163625991-d84ced43-a637-4e14-8b31-bb076f78f7a0.jpg)
![20220415214800_1](https://user-images.githubusercontent.com/78094144/163625993-986247ac-d43b-4171-b811-7b8a7ca5f893.jpg)

**Comment by alezm00** [comment]
Ciao 2 domande veloci:
- per rimane bloccato intendi che come se si aprisse ma non lo vedi?
- che tipo di tastiera hai? (italiana, americana)

**Comment by rendy6416** [comment]
@tonin994

**Comment by tonin994** [comment]
Esatto si apre, infatti esce anche il puntatore del mouse e non si riesce a vedere
 La tastiera è con layout italiano ed è della Razer

**Comment by Gregosso** [comment]
Ho cercato in tutti i modi di replicare questo problema per 3 giorni, ma non c'è stato verso, allora io chiudo la issue, poichè penso sia stato un problema passeggero, se si ripresenta non esitare a riaprire la issue
