### ISSUE TITLE
Bug grafico fucil-radio

### ISSUE THREAD

**Issue by fedegram** [ProjectHorizonRP/public_issues#130]
Segnalo questo bug grafico. Succede con tutte le armi, se le si tiene in mano per poi usare il tasto rapido assegnato alla radio si crea questo magnifico oggetto, il fucil-radio.

![image](https://user-images.githubusercontent.com/102924513/163689081-2ab214dd-055c-4146-9935-d4fd2d1b00d0.png)

**Comment by Gregosso** [comment]
Eh,  questa cosa la so, ma non ci possiamo fare molto, l'unica cosa che ti posso dire è di non utilizzare la radio con un'arma in mano
