### ISSUE TITLE
Problema bloccante minatore

### ISSUE THREAD

**Issue by stubfx** [ProjectHorizonRP/public_issues#132]
![image](https://user-images.githubusercontent.com/14958556/163705606-2969337b-5b41-4f7b-8e59-2af32f471f04.png)

**Comment by stubfx** [comment]
Uscendo e rientrando dal lavoro il problema si sistema

**Comment by Gregosso** [comment]
Sembra che questo problema non si sia più verificato. Quindi secondo me è stato un bug momentaneo, fivem è sempre fivem.
