### ISSUE TITLE
Meccanico

### ISSUE THREAD

**Issue by SorryImFrosty** [ProjectHorizonRP/public_issues#134]
**Nome su Discord**
Frosty. :(

**Descrivi il problema**
Il Menù Della Lista Dei Dipendenti si è rotto (prima volta che mi succede) ho dovuto riavviare fivem

**Come riprodurre**
Passaggi per riprodurre il problema:
1. Vai a 'Stanza capo Officina'
2. Interagisci con 'Menu capo officina'
3. Clicca su 'Lista Dipendenti'
4. Hai errori in console? (se si, fai uno screenshot)
![unknown](https://user-images.githubusercontent.com/14958556/164009298-4f37c37b-888c-4361-8492-ceb673c2da1d.png)

**Comportamento desiderato**
Che non si rompesse

**Comment by rendy6416** [comment]
Risolto
