### ISSUE TITLE
Errore lavoro minatore

### ISSUE THREAD

**Issue by DavideDnB** [ProjectHorizonRP/public_issues#136]
DavideDnB

**Descrivi il problema**
al lavoro del minatore, anche se esci dal servizio, i punti del lavoro non vanno via e si può tranquillamente lavorare senza divisa e senza piccone.
![Screenshot (1889)](https://user-images.githubusercontent.com/103921772/163766796-0124ab87-1e7e-4194-9bab-3e9528430bac.png)

**Comment by rendy6416** [comment]
@DavideDnB Ciao, hai consegnato il piccone e poi sei uscito dal lavoro, giusto?

**Comment by DavideDnB** [comment]
si si

**Comment by Gregosso** [comment]
Vorrei ricordare inoltre che non è consentito nel server l'utilizzo del mirino a schermo (Lo si considera come cheating) per questa volta però chiudiamo un'occhio, non vuol dire però che puoi usarlo ovviamente.

**Comment by DavideDnB** [comment]
> Vorrei ricordare inoltre che non è consentito nel server l'utilizzo del mirino a schermo (Lo si considera come cheating) per questa volta però chiudiamo un'occhio, non vuol dire però che puoi usarlo ovviamente. @DavideDnB

Ok pardon, appena rientro tolgo.

**Comment by rendy6416** [comment]
Provato e riprovato, Questo problema non si è più presentato
