### ISSUE TITLE
Interfaccia dj al primo login?

### ISSUE THREAD

**Issue by stubfx** [ProjectHorizonRP/public_issues#139]
Appare per 10/20 secondi poi scompare da sola, potrebbe essere legato al puntatore invisibile
![image](https://user-images.githubusercontent.com/14958556/163977864-1e8ce03d-f7f2-4702-9ae6-eac3237089ef.png)

**Comment by sasy992** [comment]
Ultimamente non si è più verificato (a me) questa schermata, non so se può essere utile

**Comment by Gregosso** [comment]
Abbiamo aggiornato lo script del DJ, non dovrebbe più apparire la console, io chiudo questa issue.
