### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SorryImFrosty** [ProjectHorizonRP/public_issues#140]
**Descrivi il problema**
Dopo aver cliccato "join" il gioco è crashato

**Come riprodurre**
Passaggi per riprodurre il problema:
1. Apri Fivem
2. Entra nel server

**Comportamento desiderato**
Mi aspettavo entrasse nel server

**Screenshots**
![image](https://user-images.githubusercontent.com/102393018/163977939-38c5720b-b7c7-4b9c-8ba2-b4bdef5fff2b.png)

[CfxCrashDump_2022_04_19_09_51_12.zip](https://github.com/ProjectHorizonRP/public_issues/files/8511904/CfxCrashDump_2022_04_19_09_51_12.zip)

**Comment by sasy992** [comment]
Hai provato a riavviare fivem?

**Comment by alezm00** [comment]
Fivem e' "instabile" e non possiamo identificare ogni tipo di crash del gioco. 
Controllando il dump ho visto che non risulta alcun errore dovuto al server anzi il log si interrompe durante il download di uno script (cosa gestita interamente dal gioco e non da noi)

Siamo felici di aiutare il piu' possibile se il problema persiste non esitare a entrare in attesa supporto in caso di ulteriori problemi
