### ISSUE TITLE
Add MDT su tasto rapido

### ISSUE THREAD

**Issue by salvatore-disavio** [ProjectHorizonRP/public_issues#141]
Aggiungere l'MDT su un tasto rapido

**Comment by alezm00** [comment]
Intanto che questa cosa viene implementata rimando al messaggio che sasy ha mandato su discord:

Per poter settare l'MDT su un tasto rapido: aprire la console con F8, incollare questo bind keyboard PAGEUP mdt (se non va, questo: bind keyboard PAGEUP "mdt") e vi setta l'MDT sul tasto PAGE UP
Se al posto del PAGEUP volete un altro tasto lo trovate qui https://docs.fivem.net/docs/game-references/controls/, basta sostituirlo
