### ISSUE TITLE
Mancata texture nell'inventario polizia

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#15]
manca l'immagine della torcia uv
![2022-03-26 09_37_22-FiveM -  ITA  Project Horizon  TEST SERVER](https://user-images.githubusercontent.com/102382815/160231837-4823f588-b235-44da-b3ee-3b0ebf2e5e3b.png)

**Comment by mrkiko144** [comment]
Aggiunto icona item torcia uv

**Comment by mrkiko144** [comment]
Aggiunto icona uvlight
