### ISSUE TITLE
BUG Eurotruck

### ISSUE THREAD

**Issue by sasy992** [ProjectHorizonRP/public_issues#151]
Dopo aver comprato camion ed Autista per un totale di 500k il mio Eurotruck mi da circa 60$ ogni mezz'ora... Servirebbero almeno 5000 ore per poter riprendere i soldi spesi.
Secondo me dovrebbe pagare un minimo di 5k fino a 10k random per ogni consegna, sennò non ha senso di comprare un veicolo ed un autista

**Comment by rendy6416** [comment]
@sasy992 Intendi dire che paga troppo o troppo poco?

**Comment by sasy992** [comment]
Paga troppo poco.
Un prezzo corretto sarebbe di ALMENO 7K ogni 15/30 mezz'ora.. Ma proprio come minimo, sennò non ha senso comprare l'eurotruck
