### ISSUE TITLE
Tempo Automatico di Respawn Eccessivo quando l'ems non e' in citta'

### ISSUE THREAD

**Issue by theycallmemisha** [ProjectHorizonRP/public_issues#152]
Nome Discord: Misha

Il tempo di respawn a 30 minuti mi sembra leggermente eccessivo se nessuno tra admin o EMS e' disponibile per curare, se succede in live, la live e' bloccata per un periodo troppo lungo.

**Comment by Gregosso** [comment]
A quanto lo metteresti te?

**Comment by theycallmemisha** [comment]
Credo che in meno di 10 minuti se inoltrata la chiamata all' EMS siano in grado di raggiungere e identificare il ferito, quindi proverei con 10 minuti, se poi il tempo non e' sufficiente per loro allora 15.

**Comment by sasy992** [comment]
@Gregosso If (medici online>1) tempo_respawn=15 min, Else  tempo_respawn=8 min

**Comment by stubfx** [comment]
if (mia nonna ha le palle) then mia nonna = flipper

**Comment by sasy992** [comment]
Hai imparato anche tu a scriptare.. bravo! Wecolme in the club

**Comment by sasy992** [comment]
Oggi è successo di nuovo, mezz'ora persa.. Vorrei sollecitare l'importanza di questa issues. 
è davvero bloccante

**Comment by stubfx** [comment]
Sistemato, se il player muore e non ci sono medici online, il timer scende automaticamente a 5 minuti.
