### ISSUE TITLE
Bug antenna veicolo polizia

### ISSUE THREAD

**Issue by fedegram** [ProjectHorizonRP/public_issues#157]
Appena tirato fuori il veicolo dal garage della centrale vorrei aprire il menù di gestione dell'antenna. Purtroppo finisce che il 90% delle volte non funziona, anche provando a modificare il tasto assegnato allo stesso. Spesso quando Grego è online riesce a porre rimedio, il fatto è che non capisco se il problema sono io oppure è il menù stesso ad essere buggato. 
Purtroppo è un menù utile, soprattutto per identificare veicoli ricercati.

**Comment by stubfx** [comment]
provo a dare un occhiata nel pomeriggio

**Comment by Gregosso** [comment]
Ci sono novità in merito @stubfx ?

**Comment by stubfx** [comment]
Ho dimenticato la issue, me la segno e la controllo @Gregosso

**Comment by stubfx** [comment]
@fedegram a me e @Gregosso il menu di antenna si apre correttamente, hai per caso un veicolo specifico da provare?
