### ISSUE TITLE
Nuovo Veicolo Ford F-450

### ISSUE THREAD

**Issue by SoraHarlock** [ProjectHorizonRP/public_issues#159]
**Nome su Discord**
@👑Capt. Sora Harlock👑#3297

**Descrivi la tua idea**
(https://www.gta5-mods.com/vehicles/2019-f450-superduty-platinum-4-door-tow-truck-pack-fivem)

Tow Truck Ford F450 per Polizia, Meccanici e Pompieri Forse.
![Screenshot (418)](https://user-images.githubusercontent.com/50340734/164719083-0bd938ad-5107-47bb-90ad-252d01462bd6.png)

**Comment by rendy6416** [comment]
![image](https://user-images.githubusercontent.com/82285888/164890397-0d618a42-57a1-48de-b4fa-4d3fbd2c04d9.png)

**Comment by rendy6416** [comment]
è gia presente un veicolo in gioco di questo tipo :)
