### ISSUE TITLE
kick dal server bodycam

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#161]
mi ha buttato fuori dal server dando questo errore
![image](https://user-images.githubusercontent.com/102382815/164786192-c792d00f-da9e-4573-b517-bcb5a2a079d5.png)

**Comment by stubfx** [comment]
Potrebbe essere che lo script della bodycam stia provando a mandare fin troppi pacchetti, se succede di nuovo consiglio di non usarla finche non la aggiorniamo
