### ISSUE TITLE
non si possono mettere i "flag" ai veicoli

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#163]
dal tablet della polizia non si possono mettere i warrants ai veicoli 
![image](https://user-images.githubusercontent.com/102382815/164816607-0543cd0a-baad-4d2e-94c7-d6923fe44ac0.png)

**Comment by stubfx** [comment]
non ti permette di scrivere nel campo di testo o è una feature mancante?

**Comment by sasy992** [comment]
Stesso problema già riportato qui: [Qui](https://github.com/ProjectHorizonRP/public_issues/issues/150)

**Comment by Gregosso** [comment]
Issue duplicata, la chiudo e continiuamo sulla #150
