### ISSUE TITLE
Morte istantanea allo spawn

### ISSUE THREAD

**Issue by meteor88762** [ProjectHorizonRP/public_issues#164]
Non appena sono rientrato in città sono morto senza alcun motivo, cosi per 2 volt
![FiveM® by Cfx re -  ITA  Project Horizon _ NUOVA APERTURA _ projecthorizon it _ FULL RP _ 🔒 Whitelist  _ 🎤 ingame-voice _ LSPD _ LSFD _ 🇺🇸 Based _ WHITELIST --_ projecthorizon it 23_04_2022 12_06_36](https://user-images.githubusercontent.com/102412281/164890088-2a826062-cf41-4ff2-bd6c-6c8bcbd909ff.png)

**Comment by stubfx** [comment]
Potrebbe essere legata al visn_are @Gregosso ?

**Comment by sasy992** [comment]
Se può essere utile: mi è capitata la stessa identica cosa

**Comment by Gregosso** [comment]
Dovrei aver fixato questo problema forse, bisogna attendere dei riscontri.  Intanto metto la issue on hold, se si ripresenta questo problema vedrò come risolvere 🗡️

**Comment by mrkiko144** [comment]
Dato che il problema non persiste chiudo la issue
