### ISSUE TITLE
Ospedale garage

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#17]
mancano i veicoli EMS, ed in più una delle 3 porte per entrare nel garage dalla struttura non è apribile
![2022-03-26 10_17_59-FiveM -  ITA  Project Horizon  TEST SERVER](https://user-images.githubusercontent.com/102382815/160233178-fdf3e6b2-8d02-49d0-88d7-bfbdfc065c9e.png)

![2022-03-26 10_19_45-FiveM -  ITA  Project Horizon  TEST SERVER](https://user-images.githubusercontent.com/102382815/160233181-cdc7dd09-fd92-4ef5-8601-b0ea24b8c234.png)

**Comment by Enderic3** [comment]
ed forse (non lo ho trovato) il blip per entrare/uscire di servizio, ed mancano i vestiti

**Comment by rendy6416** [comment]
I veicoli verranno aggiunti nei prossimi giorni.
Verificherò le porte non apribili ed infine verranno aggiunti tutti i marker mancanti

**Comment by stubfx** [comment]
I veicoli sono stati aggiunti, dobbiamo sistemare solo le porte @rendy6416

**Comment by rendy6416** [comment]
Ospedale tutto pronto
