### ISSUE TITLE
lo script del DJ del night club non permette di abbassare il volume la musica 

### ISSUE THREAD

**Issue by Scodrim99** [ProjectHorizonRP/public_issues#176]
**Nome su Discord**
Scodrim

**Descrivi il problema**
tutte le volte che metto la musica sulla console da dj nel night club la musica viene sparata al massimo è non si può abbassare la musica anche se sono presenti i tasti per abbassare la musica 

in più chiedo se si può implementare lo script da dj anche nel festival bus

**Comment by rendy6416** [comment]
@Scodrim99  Ho provato ora e funziona perfettamente, inoltre Lo script da dj è fattibile solo in luoghi fissi. Per quello si puo vedere un altra soluzione

**Comment by stubfx** [comment]
Potrebbe essere possibile aggiungerlo anche come radio.

**Comment by stubfx** [comment]
Sposto la issue in enhancement perche il bug è stato risolto, da lavorare solo su 

"in più chiedo se si può implementare lo script da dj anche nel festival bus"

**Comment by Scodrim99** [comment]
volevo chiedere se è possibile abbassare di qualche decibel la musica erogata dallo script da dj dato che è troppa invasiva è non permette lo svolgimento di roleplay tra diversi player
