### ISSUE TITLE
Le mie macchine e garage sono scomparsi

### ISSUE THREAD

**Issue by meteor88762** [ProjectHorizonRP/public_issues#179]
*Meteor su discord 
Xavier Foster su Fivem

Appena sono tornato in città sono uscito di casa per prendere uno dei miei veicoli dal garage ma il blip era scokparso e con esso i miei veicoli

**Comment by rendy6416** [comment]
@meteor88762 Quando torni vediamo assieme cosè successo

**Comment by Gregosso** [comment]
@meteor88762 hai ancora questo problema o è stato risolto ?
