### ISSUE TITLE
Bug banca duplicazione

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#18]
Andare al blip della banca, fare deposita arma, depositare un arma, quest'ultimo sarà aggiunto all'inventario della banca ma non tolto dal proprio inventario, però lo si può riprendere l'oggetto duplicandolo

**Comment by rendy6416** [comment]
Verrà risolto cambiando il tipo di deposito della banca

**Comment by rendy6416** [comment]
Impostato tipo di deposito correttamente, ora funzionante.
