### ISSUE TITLE
Bug vendita veicoli

### ISSUE THREAD

**Issue by sasy992** [ProjectHorizonRP/public_issues#181]
Quando si vende un veicolo, sia al concessionario che alla stazione di polizia quest'ultimo viene venduto e poi riappare sul blip. 
Capita, ogni tanto, anche quando si mette in garage.
![image](https://user-images.githubusercontent.com/30809172/165298392-f6ea6b1b-2b89-4a11-ac23-260400255d5d.png)

**Comment by Gregosso** [comment]
Mi sa che potrebbe essere il sistema di persistenza dei veicoli non configurato in maniera ottimale su questo script, invito quindi @alezm00 a darci un'occhiata

**Comment by alezm00** [comment]
[commit 9ed3112e61e19b3aa503e9b5b639097a0406e30c](https://github.com/ProjectHorizonRP/fivem/commit/9ed3112e61e19b3aa503e9b5b639097a0406e30c)
