### ISSUE TITLE
Bug prelevare veicolo centrale polizia

### ISSUE THREAD

**Issue by fedegram** [ProjectHorizonRP/public_issues#183]
Ho incontrato questo curiosissimo bug. Ovvero non esiste più il marker in centrale per prelevare veicoli. Ovvio che ne potrei comprare a bizzeffe, ma non credo sia la soluzione migliore.
![image](https://user-images.githubusercontent.com/102924513/165374195-d40ecab1-8ca7-4dc2-bbb8-4cd97cebaa84.png)

**Comment by sasy992** [comment]
Io lo vedo

**Comment by Gregosso** [comment]
Penso che ogni tanto a lato client il marker non venga renderizzato, si potrebbe magari provare se allontanandosi dal marker o riavviando fivem il problema si risolve. Chiudo questa issue, al massimo se si ripresenta questo problema invito a riaprila 👯
