### ISSUE TITLE
Problema inventario

### ISSUE THREAD

**Issue by Giaccari** [ProjectHorizonRP/public_issues#185]
Il mio discord è:  💜𝕁𝕒𝕔𝕜𝕒𝕣𝕚💜#7295 

il problema sopraggiunge nel momento in cui io, per esempio, devo togliere o mettere una maschera, di norma dovrei cliccare sul tasto col simbolo della maglietta nell'inventario, però, andando a cliccare questo tasto, non viene aperto il menu per la gestione del personaggio ma bensì si chiude completamente l'inventario. Ho provato anche con gli altri tasti presenti nell'inventario e funzionano tutti tranne il tasto accanto all'ingranaggio delle impostazioni. 

premere il tasto "Y"
scorrere con il mouse fino all'icona col simbolo della maglietta
cliccare sull'icona

quello che mi sarei aspettato era l'apertura di un menu gestione per poter togliere la mia maschera, cosa che non è accaduta.

non è possibile per me aggiungere screenshot in quanto non è un bug al quale si possono fare foto essendo che l'unica cosa che fa è chiudere l'inventario invece di aprire il menu gestione outfit.

Ringrazio tutto lo staff in anticipo per l'aiuto che mi offriranno.

**Comment by rendy6416** [comment]
@Giaccari Ciao, secondo me potrebbe essere che hai attivato nelle impostazioni dell'inventario la modalità "fai click e chiudi"
Prova ad andare nell'inventario, schiaccia il tasto della rotella in basso a sinistra e a destra hai "fai click e chiudi"

**Comment by Gregosso** [comment]
@Giaccari il probelma è stato risolto ?

**Comment by theycallmemisha** [comment]
Se non vado errato mi ha detto in ds che ha risolto dopo le direttive di @rendy6416

**Comment by Gregosso** [comment]
> Se non vado errato mi ha detto in ds che ha risolto dopo le direttive di @rendy6416

Ottimo, allora chiudo la issue
