### ISSUE TITLE
Comando Tow

### ISSUE THREAD

**Issue by Timo43** [ProjectHorizonRP/public_issues#197]
Ha volte come mi é successo ieri in streaming il veicolo quando eseguo il comando tow rimane in strada e non lo si vede sul veicolo e come info esce: Veicolo é stato caricato correttamente. Se rifaccio il comando tow esce: Il veicolo é stato scaricato correttamente. 
Malgrado questo il veicolo resta a terra anche se ri eseguo il comando più volte.

**Comment by mrkiko144** [comment]
Comando tow ora funziona
