### ISSUE TITLE
tipo di patenti

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#199]
guardando le varie licenze dei player ho notato che  ci sono patenti doppie
![{B9E66E55-D718-4B9E-8076-7D5AAE21F675}](https://user-images.githubusercontent.com/102382815/169672598-965e2207-944b-4aae-bc5e-9cd15a3acacc.png)

**Comment by Gregosso** [comment]
Risolto con la prox hotfix
