### ISSUE TITLE
hud macchina al di fuori della macchina

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#200]
anche dopo esser sceso dalla macchina rimare hud che segna lo stato della benzina del motore
![{B3E2EEBC-9E6D-4CF7-A833-79C43940E0AE}](https://user-images.githubusercontent.com/102382815/169672610-aae8c56e-4670-45ee-a766-d002e51407c4.png)

**Comment by alezm00** [comment]
fixato online al prossimo merge
