### ISSUE TITLE
Rapina gioielleria

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#22]
se uno starta la rapina arriva la notifica alla polizia, se poi arriva un'altra persona e spara prima del fine del countdown la rapina non parte però arriva la notifica alla polizia

**Comment by stubfx** [comment]
Quando si starta la rapina alla gioielleria l'allarme continua all'infinito
l'allarme va in loop per tutti quelli che erano sul posto al momento dell'avvio, se qualcuno si avvicina dopo non sente niente.

**Comment by stubfx** [comment]
Controllare eventuali update/sostituzioni lo script sembra essere datato.

**Comment by stubfx** [comment]
L'unica sostituzione nel mercato aggiunge poco e niente facendo diventare a pagamento uno script open source, ci lavoro che almeno sappiamo come è fatto il codice.

**Comment by stubfx** [comment]
L'unica sostituzione nel mercato aggiunge poco e niente facendo diventare a pagamento uno script open source, ci lavoro io che almeno sappiamo come è fatto il codice.
