### ISSUE TITLE
errore in console da sceriffo

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#24]
![2022-03-26 14_14_44-FiveM -  ITA  Project Horizon  TEST SERVER](https://user-images.githubusercontent.com/102382815/160241173-36b6a8ab-8ec4-4b0d-8c8e-28099fbd9d42.png)

**Comment by stubfx** [comment]
Stesso errore girando completamente a random
![image](https://user-images.githubusercontent.com/14958556/160241824-e800843d-45dc-4c0b-8aec-e7bbe0c608f2.png)

**Comment by stubfx** [comment]
Risolto, mancava del testo nel file config.

**Comment by stubfx** [comment]
https://github.com/ProjectHorizonRP/fivem/commit/9530b74b8009e87267d12d02cbf952b46cdb2f5b
