### ISSUE TITLE
Modifica alla casa: impossibile spostare oggetti.

### ISSUE THREAD

**Issue by meteor88762** [ProjectHorizonRP/public_issues#25]
**Descrivi il problema**
Inserisci una descrizione chiara e dettagliata del problema riscontrato.

**Come riprodurre**
Passaggi per riprodurre il problema:
1. Vai a '...'
2. Interagisci con '....'
3. Clicca su '....'
4. Hai errori in console? (se si, fai uno screenshot)
(Ricorda che puoi fare uno screenshot con Win + Shift + S e incollare qui direttamente con Ctlr + V)

**Comportamento desiderato**
Una descrizione chiara del comportamento che ti saresti aspettato

**Screenshots**
Se possibile, aggiungi screenshot del problema.
(Ricorda che puoi fare uno screenshot con Win + Shift + S e incollare qui direttamente con Ctlr + V)

**Comment by rendy6416** [comment]
Si possono spostare gli oggetti, guarda attentamente il menu delle informazioni "aiuto" e verifica una seconda volta

**Comment by meteor88762** [comment]
Già fatto mentre parlavo con stub

Il Sab 26 Mar 2022, 20:04 rendy6416 ***@***.***> ha scritto:

**Comment by stubfx** [comment]
@meteor88762 appena hai verificato il problema potresti nel caso chiudere la issue pls? thanks

**Comment by SorryImFrosty** [comment]
Verificato: Ok

**Comment by stubfx** [comment]
Verificato OK
