### ISSUE TITLE
Bug pompieri tubo attaccato all'idrante

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#36]
se distruggo un idrante posso comunque prendere il tubo sia dal prop idrante che da dove schizza l'acqua
![image](https://user-images.githubusercontent.com/102382815/160259474-bf86485e-d6ac-4c28-902b-60571d99b418.png)
![image](https://user-images.githubusercontent.com/102382815/160259478-73492110-f44c-4bb7-9754-8a1dc5840c30.png)

**Comment by rendy6416** [comment]
Problema legato alla fisica di gta
