### ISSUE TITLE
piove dentro casa

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#38]
![image](https://user-images.githubusercontent.com/102382815/160259988-ccae7bbf-a5ae-4087-b285-b5e48d5b19c7.png)

**Comment by Gregosso** [comment]
Siamo in attesa del supporto tecnico

**Comment by rendy6416** [comment]
Aggiornamento eseguito, ora è solo da testare il funzionamento

**Comment by stubfx** [comment]
Provato OK
