### ISSUE TITLE
Cambio immagine del ferilizzante

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#39]
cambiare la texture del fertilizzante delle piante, magari mettere del terriccio o comunque qualche polvere
![{78F19FB6-A4C9-41AE-A988-FD599D8EDD78}](https://user-images.githubusercontent.com/102382815/160260143-fcb3ecda-aa6b-4641-bb11-651dc37b6519.png)

**Comment by mrkiko144** [comment]
Sostituito icona fertilizzante
