### ISSUE TITLE
fix gui del postino e aggiunta di garage per polizia

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#40]
fixxare la gui del postino che è totalmente diversa da tutto il resto del server
![image](https://user-images.githubusercontent.com/102382815/160260339-69044cdf-d8a2-4026-9df6-7e9711cd5d29.png)

aggiungere garage alla polizia al civico:

8090 
![image](https://user-images.githubusercontent.com/102382815/160260474-559e20fb-6be2-4791-acb8-f9340ae8eedf.png)

9148
![image](https://user-images.githubusercontent.com/102382815/160260555-18790660-aa35-4f6c-9883-11418f552d43.png)

7104
![image](https://user-images.githubusercontent.com/102382815/160260618-225b3920-2abf-4af9-89b6-230e5091bad2.png)

3004
![image](https://user-images.githubusercontent.com/102382815/160260732-71266e0e-5f92-478b-92bb-a71f11b5751a.png)

**Comment by stubfx** [comment]
ender chiede anche garage normali ma solo per auto polizia
