### ISSUE TITLE
Fatture lavoro Import

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#42]
se si è dell'import con f6 si apre il menù per fare le fatture, una volta rilasciata l'utente non la ritrova da nessuna parte, ed se si prova a fare la fattura con il punto di domanda non da l'opzione per crearne una 
![image](https://user-images.githubusercontent.com/102382815/160276456-2769c4e7-3bbb-4640-9264-62283798d6b3.png)
![image](https://user-images.githubusercontent.com/102382815/160276459-364a8aba-1f28-4c92-b314-7be9608c1956.png)

**Comment by stubfx** [comment]
Non sono certo che questo menu sia necessario @Gregosso , dovrebbe essere rimosso?
