### ISSUE TITLE
silenziatore pistola

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#44]
il silenziatore se montato sulla pistola funziona, però nel momento che salgo su una macchina e sparo il silenziatore e come se non ci fosse

**Comment by SorryImFrosty** [comment]
Verificato: KO, il silenziatore scompare quando sali sulla macchina e ritorna quando scendi
però sulle moto rimane

**Comment by stubfx** [comment]
Si comporta nello stesso modo nei server freeroam di FiveM, sembra infatti essere un bug di GTA5.
