### ISSUE TITLE
Auto appena acquistata non intestata a me

### ISSUE THREAD

**Issue by SorryImFrosty** [ProjectHorizonRP/public_issues#46]
![image](https://user-images.githubusercontent.com/102393018/160361398-a08bf5f5-40b1-45cb-a63c-8d981551082c.png)
Ho comprato questo veicolo, provando a depositarlo nel garage ho notato che non veniva depositato, settandomi poliziotto ho notato che la macchina era intestata a "Sconosciuto"

**Comment by alezm00** [comment]
In quale shop é stato comprato? Hai fatto delle modifiche al veicolo?

**Comment by stubfx** [comment]
Appena verficato OK, lo stato di @SorryImFrosty a db era instabile.
