### ISSUE TITLE
non funziona e mancata traduzione nel menù "opzioni faccia avanzate"

### ISSUE THREAD

**Issue by orsini-203** [ProjectHorizonRP/public_issues#48]
orsini_203

mancata traduzione nel menù "opzioni faccia avanzate" nel menù di creazione del PG
e il menù stesso non funziona

![image](https://user-images.githubusercontent.com/60648231/160469406-0d399ba6-2971-4316-be24-267ec1b02632.png)

**Comment by stubfx** [comment]
Il menu è stato tradotto e funziona correttamente
![image](https://user-images.githubusercontent.com/14958556/160552455-da4f564b-1899-4447-a21a-6d3b26059725.png)
