### ISSUE TITLE
operatore ecologico

### ISSUE THREAD

**Issue by orsini-203** [ProjectHorizonRP/public_issues#50]
lavoro operatore ecologico

bisogna settare i vestiti per il lavoro, ora sono impostati come se fossi civile

![image](https://user-images.githubusercontent.com/60648231/160495231-6a37276a-6940-42ef-9faa-ff59f077dc7f.png)

**Comment by stubfx** [comment]
https://docs.fivem.net/natives/?_0x262B14F48D29DE80

**Comment by Enderic3** [comment]
dovrebbe essere risolto, ho provato oggi il lavoro ed avevo le braccia

**Comment by Enderic3** [comment]
io direi fixxato 
![image](https://user-images.githubusercontent.com/102382815/162043532-ca4c2c5a-dd4f-40af-b6ff-6ac3d414467c.png)

**Comment by stubfx** [comment]
@Gregosso @Enderic3 i vestiti che vedete sono di test, non sono quelli finali, @Gregosso prendi il json che vedi dei vestiti e modifica quello che funziona

**Comment by Gregosso** [comment]
fixed 👯
