### ISSUE TITLE
Chiavi casa 

### ISSUE THREAD

**Issue by Ceronte-Rino** [ProjectHorizonRP/public_issues#55]
**Nome su Discord**
Sam
**Descrivi il problema**
 quando passi le chiavi di casa a un giocatore, da il messaggio che le hai passate ma non le passa effettivamente, se non dopo il riavvio di FiveM, se lo fai di nuovo, dice che il giocatore ha gia le chiavi
quando si "hanno" le chiavi non si puo aprire deposito e guardaroba fino al riavvio di fivem

con la pioggia attiva si bagna il pavimento

**Come riprodurre**
Passaggi per riprodurre il problema:
1. Vai a 'casa'
2. Interagisci con 'dai le chiavi a un giocatore'
3. Il giocatore con le chiavi Clicca su 'esci'
4. Hai errori in console? (se si, fai uno screenshot)
(Ricorda che puoi fare uno screenshot con Win + Shift + S e incollare qui direttamente con Ctlr + V)

**Comportamento desiderato**
Una descrizione chiara del comportamento che ti saresti aspettato

**Screenshots**
Se possibile, aggiungi screenshot del problema.
(Ricorda che puoi fare uno screenshot con Win + Shift + S e incollare qui direttamente con Ctlr + V)

**Comment by rendy6416** [comment]
#38

**Comment by rendy6416** [comment]
Aggiornamento eseguito, ora riprovate e avvisatemi se è funzionante

**Comment by stubfx** [comment]
Provato OK
