### ISSUE TITLE
Pompieri appoggiati su muri inesistenti

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#57]
alla centrale dei pompieri spawnano dei pompieri appoggiati a un muro invisibile
![image](https://user-images.githubusercontent.com/102382815/161307838-6e0b717d-20aa-4567-acdb-cdf9e217ffa7.png)

**Comment by stubfx** [comment]
stanno chillando male

**Comment by Enderic3** [comment]
> stanno chillando male

licenziati

**Comment by rendy6416** [comment]
veranno rimossi gli npc negli edifici pubblici
