### ISSUE TITLE
Spawnano veicoli dentro al concessionario

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#58]
spawnano auto vanilla che si possono rubare dentro al concessionario
![image](https://user-images.githubusercontent.com/102382815/161308789-19138884-d05e-409b-a161-de70a23d569e.png)

**Comment by stubfx** [comment]
si possono rubare?

**Comment by stubfx** [comment]
Per noi è preferibile vedere comunque dei veicoli che sembrino realistici per il mercato all'interno del concessionario piuttosto che vedere uno spazio vuoto, nel caso uno dei veicoli venisse rubato sarà compito della polizia recuperare e multare il ladro.
