### ISSUE TITLE
traduzione pulizia soldi

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#59]
c'e da  tradurre il messaggio che esce quando lavi i soldi sporchi
![image](https://user-images.githubusercontent.com/102382815/161311407-5745070f-6925-4f01-94ee-dca4f786cd3c.png)

**Comment by Enderic3** [comment]
anche quando chiudi e apri l'auto ce da tradurre
![image](https://user-images.githubusercontent.com/102382815/161344911-ce88e261-66de-4deb-b4ea-1d43e6027396.png)
![image](https://user-images.githubusercontent.com/102382815/161344921-ec1113a7-a72d-4868-a785-3eba13c138b9.png)

**Comment by rendy6416** [comment]
Traduzioni delle chiavi effettuate

**Comment by rendy6416** [comment]
Traduzioni chiavi effettuata

**Comment by Enderic3** [comment]
arrore nella traduzione del messaggio per rinominare le chiavi: esce scritto NOMEW
![image](https://user-images.githubusercontent.com/102382815/161559259-28d20c38-50f3-4887-a2e7-87f9db5feabb.png)

**Comment by Enderic3** [comment]
fixxato
![image](https://user-images.githubusercontent.com/102382815/162044056-0cb211d5-1354-42bf-b062-a77227d0218c.png)

**Comment by rendy6416** [comment]
Credo che ci sia uno spirito che abbia fatto questo per noi ahah, siamo in attesa del supporto lo stesso perchè mancano altre traduzioni
