### ISSUE TITLE
Schermata nera al concessionario

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#60]
Quando si apre il negozio del concessionario c'è la possibilità che dia schermo nero

**Comment by stubfx** [comment]
Chiedere al supporto?

**Comment by rendy6416** [comment]
> @Gregosso abbiamo notizie dal supporto?

Al momento sono in contatto io con il supporto, stanno valutando cosa può causare l'errore

**Comment by stubfx** [comment]
Non piu riproducibile.
