### ISSUE TITLE
errore in console

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#63]
errore script core_vehicle
![image](https://user-images.githubusercontent.com/102382815/161345082-a5f56e51-26bc-4a53-a130-542770b43c7a.png)

**Comment by rendy6416** [comment]
Al momento non è chiaro come sia uscito questo errore.
@Enderic3 è possibile avere una spiegazione più chiara su come replicare questo errore?

**Comment by Gregosso** [comment]
Dato che non ci è stata data nessuna spiegazione, chiudo la issue, se si ripresenta crearne una nuova più dettagliata
