### ISSUE TITLE
core vehicle non si apre

### ISSUE THREAD

**Issue by Ceronte-Rino** [ProjectHorizonRP/public_issues#64]
non rileva niente
![image](https://user-images.githubusercontent.com/102462536/161346162-35f7dc0c-547a-4120-af11-76416a5421ee.png)

**Comment by Ceronte-Rino** [comment]
il problema è dovuto ai veicoli che non marcano i km (comprati non rubati)

**Comment by stubfx** [comment]
potrebbe essere correlato #63
