### ISSUE TITLE
errore in console con i documenti

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#65]
stavamo testando il passaggio di proprietà e i documenti ha dato questo errore, in più i documenti si cancellano al riavvio del client
![image](https://user-images.githubusercontent.com/102382815/161378374-df4e2bf4-06f7-43c6-81b4-b68fa95c428d.png)

**Comment by rendy6416** [comment]
Il problema dopo il riavvio del client è stato sistemato, verificare anche per favore se funziona il passaggio del documento correttamente @Enderic3
