### ISSUE TITLE
Fatture banca pagate in contanti

### ISSUE THREAD

**Issue by Ceronte-Rino** [ProjectHorizonRP/public_issues#66]
Quando apri l'app della banca nel telefono, e hai delle fatture (solo certe pero ora non so dire quali, scusate ), le paga con i contanti invece che scalarli dalla banca

**Comment by stubfx** [comment]
Controllare se le fatture nel telefono sono allineate con il sistema di fatture che abbiamo al momento.
@Ceronte-Rino segnala che alcune delle fatture nel telefono sono molto vecchie, quindi dobbiamo chiedere al supporto se è possibile modificare il comportamento e/o eventualmente rimuovere il menu fatture nel caso non fosse comunque allineato a quello corrente.

**Comment by stubfx** [comment]
@rendy6416 ha inviato il ticket al supporto

**Comment by rendy6416** [comment]
Al momento il supporto in base alle informazioni fornite ha detto che sembrerebbe essere solo un problema di configurazione, verificheremo e appena possibile ci sarà l'aggiornamento da parte nostra

**Comment by rendy6416** [comment]
Le fatture ora si possono pagare direttamente con i soldi in banca
