### ISSUE TITLE
errore in console dopo ricarica pistola

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#67]
ho ricaricato la pistola poi ho fatto l'accesso al bancomat e mi ha dato questo errore
![image](https://user-images.githubusercontent.com/102382815/161391216-66d9181b-1c71-45df-b785-ce451de083c8.png)

**Comment by rendy6416** [comment]
Errore dovuto ad un restart dello script, ora non riproducibile in fase di produzione
