### ISSUE TITLE
problema conflitto tasto G

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#68]
premendo il tasto U si apre il menù delle chiamate di polizia medico e pompieri, ma poi premendo G per rispondere alla chiamata si apre anche il menù delle chiavi delle auto 
![image](https://user-images.githubusercontent.com/102382815/161400155-86b6f4df-557e-4da2-953d-0544df0bcb37.png)

**Comment by mrkiko144** [comment]
Se si é pompiere si apre anche il menu dei pompieri ( quello dove ti permette di equipaggiare zaini, maschera ecc)

**Comment by stubfx** [comment]
vediamo di cambiare tasto o almeno la posizione a schermo

**Comment by Gregosso** [comment]
risolto cambiando script per la gestione chiavi
