### ISSUE TITLE
 recupero un'auto dal garage

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#69]
fare che quando recuperi l'auto dal garage i soldi li prende dalla banca

**Comment by Gregosso** [comment]
in attesa del supporto

**Comment by rendy6416** [comment]
> @Gregosso abbiamo notizie dal supporto?

Contattato il supporto, stanno lavorando ad una nuova UI ed assieme a questa nei prossimi giorni mi hanno confermato che aggiungeranno questa opzione

**Comment by Gregosso** [comment]
@rendy6416 è stato fatto questo update ?
