### ISSUE TITLE
shop auto ospedale

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#70]
se vai a comprare le auto dell'ospedale con l'auto supervisore ti da quella dei pompieri
![image](https://user-images.githubusercontent.com/102382815/161418537-f3d3f598-fa1f-4a22-817d-2e77db5dbf11.png)

**Comment by Enderic3** [comment]
![image](https://user-images.githubusercontent.com/102382815/161418581-e5bb0f65-42a4-4acc-9465-09819c31a895.png)

**Comment by rendy6416** [comment]
Tutto corretto, basta cambiare in seguito la livrea
