### ISSUE TITLE
Manca texture oggetti auto smontata

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#73]
quando smonti l'auto ti da i cerchi e la batteria senza texture
![image](https://user-images.githubusercontent.com/102382815/161436818-e37111c5-2338-47ae-8c79-8d642667efd5.png)

**Comment by Enderic3** [comment]
altre texture mancanti, ed in più ogni tanto dopo la scomposizioni dell'auto rimane ed la puoi scomporre all'infinito
![image](https://user-images.githubusercontent.com/102382815/161439815-bd929a7a-ea18-42f5-b40d-ae93aaa618c0.png)

**Comment by mrkiko144** [comment]
icone mancanti aggiunte
