### ISSUE TITLE
Spawn Engine caserma pompieri al 9123

### ISSUE THREAD

**Issue by sasy992** [ProjectHorizonRP/public_issues#74]
Alla caserma dei pompieri, quella base di Gta V, al 9123 spawnano i camion dei pomieri di GTAV

![image](https://user-images.githubusercontent.com/30809172/161510275-1b691438-58f0-4763-a85d-c11dc7710fd4.png)

https://user-images.githubusercontent.com/30809172/161510275-1b691438-58f0-4763-a85d-c11dc7710fd4.png

**Comment by rendy6416** [comment]
Al momento non è presente una funzione nativa di gta per rimuovere questo tipo di veicoli, vedremo di rimuoverli in qualche modo in ogni caso
