### ISSUE TITLE
vendita item macchine smontate

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#76]
spostare vendita dei componenti delle auto smontate al civico 7326 sul retro, che è una officina che può sembrare che ricicla componenti rubati 
![2022-04-04 15_43_42-FiveM -  ITA  Project Horizon](https://user-images.githubusercontent.com/102382815/161557497-e8caa1b4-a1ff-4da1-a52b-826d59f9e905.png)

**Comment by rendy6416** [comment]
Terremo conto di questa modifica al momento il luogo attuale è giusto, se verrà richiesto più volte verra spostato
