### ISSUE TITLE
/eup is not a valid command changing room polizia

### ISSUE THREAD

**Issue by fedegram** [ProjectHorizonRP/public_issues#78]
**Nome su Discord**
Se il tuo nick su GitHub non è riconducibile a discord, aggiungilo qui pls.

**Descrivi il problema**
All'interno della changing room se si prova ad usare il plugin risulta impossibile ed esce a schermo un messaggio con /eup is not a valid command

**Come riprodurre**
Passaggi per riprodurre il problema:
1. Vai a '...'
2. Interagisci con '....'
3. Clicca su '....'
4. Hai errori in console? (se si, fai uno screenshot)
(Ricorda che puoi fare uno screenshot con Win + Shift + S e incollare qui direttamente con Ctlr + V)

**Comportamento desiderato**
Una descrizione chiara del comportamento che ti saresti aspettato

**Screenshots**
Se possibile, aggiungi screenshot del problema.
(Ricorda che puoi fare uno screenshot con Win + Shift + S e incollare qui direttamente con Ctlr + V)
![image](https://user-images.githubusercontent.com/102924513/161738390-080525c9-4d36-42cb-86a2-0357fc64e63f.png)

**Comment by Gregosso** [comment]
è stato rimosso, utilizzare la tizia che è vicino allo specchio, più lungo da usare ma è più stabile e ottimizzato
