### ISSUE TITLE
Blocco stradale per l'ingresso alla stazione di polizia

### ISSUE THREAD

**Issue by sasy992** [ProjectHorizonRP/public_issues#84]
I paletti che scendono all'entrata della caserma delle polizia si abbassano soltanto se il veicolo è vicinissimo a questi.
Andrebbe spostato il trigger qualche metro prima (come in foto) sia dall'interno che dall'esterno

![image](https://user-images.githubusercontent.com/30809172/161758421-17c3552b-56a3-488c-8f1c-578b749c8d63.png)

**Comment by Gregosso** [comment]
Its not possible, dato che il trigger è all'interno della mappa non modificabile
