### ISSUE TITLE
Ambulanze spawnano buggate

### ISSUE THREAD

**Issue by sasy992** [ProjectHorizonRP/public_issues#85]
Le ambulanze, quando prese dal Garage, spawnano senza sportelli 

![image](https://user-images.githubusercontent.com/30809172/161758861-c09b0cea-007f-4bc0-b985-e6953c747a27.png)

**Comment by rendy6416** [comment]
Questi veicoli utilizzano una funzione extra, ogni extra ha ad esempio la possibilità di aprire gli sportelli mettere oggetti ecc...
Nei prossimi giorni verrà aggiunto un menù per poter gestire tutto quanto

**Comment by sasy992** [comment]
Rendy, il veicolo spawna buggato e senza gli sportelli.. non con gli sportelli aperti

**Comment by rendy6416** [comment]
![image](https://user-images.githubusercontent.com/82285888/161816273-3a9d26ed-cb1a-4cbd-be2c-bc2ed1bd7640.png)

**Comment by rendy6416** [comment]
nei prossimi giorni come detto verrà aggiunto un menu apposito per gestire questo
