### ISSUE TITLE
Possibilità di cacciare fuori la zona di caccia

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#88]
spawano in gli animali cacciabili (quelli segnati con l'immagine rossa nella minimappa), una volta uccisi li fa scuoiare anche fuori dalla zona di caccia
![image](https://user-images.githubusercontent.com/102382815/161820139-1ae2e636-caa1-4f3b-9d73-20ad2655e7c1.png)

**Comment by Enderic3** [comment]
![image](https://user-images.githubusercontent.com/102382815/161835045-bf7408e0-b4c9-473e-ad62-ddaadbf6f6ab.png)

**Comment by Gregosso** [comment]
fixato
