### ISSUE TITLE
baule della macchina apribile dalla propria casa

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#89]
se l'auto è abbastanza vicina alla casa è possibile aprire il baule da dentro la casa
![image](https://user-images.githubusercontent.com/102382815/161836953-2f6accd5-3e10-4749-a5f1-296ebc392d0f.png)
![image](https://user-images.githubusercontent.com/102382815/161836981-913f6bbf-b06c-4035-8b0a-dece359fd1ab.png)

**Comment by Enderic3** [comment]
ho lasciato la casa aperta in caso vorreste provare

**Comment by rendy6416** [comment]
Verificato, la casa deve essere posizionata più sottoterra per evitare questo problema.
