### ISSUE TITLE
Spogliatoio Meccanico Mancante

### ISSUE THREAD

**Issue by SorryImFrosty** [ProjectHorizonRP/public_issues#90]
![image](https://user-images.githubusercontent.com/102393018/161847818-8fd5a408-7a56-4426-b348-5e73ec2ae423.png)
Manca lo spogliatoio per cambiarsi i vestiti dal meccanico
Consiglierei di metterlo alle coordinate dello screenshot

**Comment by stubfx** [comment]
ProjectHorizonRP/fivem#73

**Comment by Gregosso** [comment]
Lo spogliatoio è stato messo v1.2.2
