### ISSUE TITLE
desync benzina delle auto private

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#91]
la benzina di un veicolo è desyncata tra player e player

**Comment by rendy6416** [comment]
Quando sei è in auto in 2, ed il guidatore termina la benzina io da passeggero se prendo il suo posto rivedo l'auto con il pieno e posso andare avanti tranquillamente

**Comment by stubfx** [comment]
Sistemato con aggiornamento dello script.
