### ISSUE TITLE
CONCESSIONARIO MANCA IMMAGINE AUTO

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#93]
MANCA LA FOTO DELLA MITSUBISHI FTO GP VERSION-R
![image](https://user-images.githubusercontent.com/102382815/161936039-0ab61da8-a55f-4da4-a5b5-c0da2c474427.png)

**Comment by Enderic3** [comment]
![image](https://user-images.githubusercontent.com/102382815/161937392-b073f0a6-defc-41fe-8b21-9afc954055f8.png)

**Comment by rendy6416** [comment]
Veicoli rimossi, inseriti per errore
