### ISSUE TITLE
polizia non può mettere in macchina le persone arrestate

### ISSUE THREAD

**Issue by Enderic3** [ProjectHorizonRP/public_issues#96]
un poliziotto non può mettere in macchina un player dopo averlo ammanettato perchè manca il tasto nel menù f7
![image](https://user-images.githubusercontent.com/102382815/162045135-f0751a10-cbec-46f0-873f-388e02bc5b1f.png)

**Comment by rendy6416** [comment]
Inserito il tasto "Metti nel veicolo"
